// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-LKHvt5Nq5CGY4I9jfuaQ_b_ycxrd8Y',
    appId: '1:304141888268:web:42847b333ce3d5258cf729',
    messagingSenderId: '304141888268',
    projectId: 'petcareapp-25bd3',
    authDomain: 'petcareapp-25bd3.firebaseapp.com',
    storageBucket: 'petcareapp-25bd3.firebasestorage.app',
    measurementId: 'G-N54C4DXK2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6voKpYs6fbJpRVqqBLgy8rXSoo2tOFBs',
    appId: '1:304141888268:android:e78d829ac4b3d3588cf729',
    messagingSenderId: '304141888268',
    projectId: 'petcareapp-25bd3',
    storageBucket: 'petcareapp-25bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx0P3J1tIGLfU1z9L3zY3wmgf69hoUBiM',
    appId: '1:304141888268:ios:1dd149957432b2298cf729',
    messagingSenderId: '304141888268',
    projectId: 'petcareapp-25bd3',
    storageBucket: 'petcareapp-25bd3.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx0P3J1tIGLfU1z9L3zY3wmgf69hoUBiM',
    appId: '1:304141888268:ios:1dd149957432b2298cf729',
    messagingSenderId: '304141888268',
    projectId: 'petcareapp-25bd3',
    storageBucket: 'petcareapp-25bd3.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-LKHvt5Nq5CGY4I9jfuaQ_b_ycxrd8Y',
    appId: '1:304141888268:web:52e3245f253d66298cf729',
    messagingSenderId: '304141888268',
    projectId: 'petcareapp-25bd3',
    authDomain: 'petcareapp-25bd3.firebaseapp.com',
    storageBucket: 'petcareapp-25bd3.firebasestorage.app',
    measurementId: 'G-JFXYHP6H3J',
  );
}
